openapi: 3.0.1
info:
  title: MasonSub API - Traces
  version: 0.1.0
paths:
  /api/claimants/{id}/traces:
    get:
      summary: Get TraceHistory for a claimant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Claimant primary id or external id
      responses:
        '200':
          description: A list of trace records
          content:
            application/json:
              schema:
                type: object
                properties:
                  traces:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        claimant_id:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
                        type:
                          type: string
                        payload:
                          type: object
                        confidence:
                          type: integer
        '400':
          description: Missing id
        '404':
          description: Claimant not found
        '500':
          description: Server error
